### ISSUE TITLE
Warning output to stdout when generating docs with pdoc3

### ISSUE THREAD

**Issue by magandrez** [sinanislekdemir/payton#14]
**Describe the bug**
Running the target to build docs `make docs` outputs 2 warnings (probably related)

```
_html_mako:63: ReferenceWarning: Code reference `payton.scene.Background` in module "payton.scene" does not match any documented object.
_html_mako:63: ReferenceWarning: Code reference `payton.scene.Background` in module "payton.scene.scene" does not match any documented object.
```

**To Reproduce**
1. Run `make docs` on the root of the project.
2. See STDOUT to find the warnings generated by pdoc3.

**Expected behavior**
No warnings should be outputted to STDOUT.

**Additional context**

Build with 
  - Python 3.7.3 

Dependencies resolved as follows:  
  - pdoc3 0.5.3
  - mako 1.0.13
  - markdown 3.1.1
  - MarkupSafe 1.1.1
  - setuptools 40.8.0

**Comment by sinanislekdemir** [comment]
https://github.com/sinanislekdemir/payton/pull/16

**Comment by magandrez** [comment]
👍 

Note: The docs need to be re-built after #16
