### ISSUE TITLE
Broken link in repo description

### ISSUE THREAD

**Issue by magandrez** [sinanislekdemir/payton#15]
**Describe the bug**
Silly thing: the URL in the description of the repository points to a broken link. Probably due to the previous build path for the docs (`docs/`, instead of the standard pdoc3 `docs/<MODULE_NAME>`).

This can be fixed by, e.g.: changing the URL in the description of the repository to be `https://sinanislekdemir.github.io/payton/payton`, though, the URL seems silly. Perhaps this can be configured in Github settings for the repository.

**To Reproduce**
1. Click on the link in the description of the repo (https://sinanislekdemir.github.io/payton/)
2. Opens browser tab and outputs 404 as a result of not finding any `index.html`

**Expected behavior**
Click on the description link opens the documentation for Payton.

**Comment by sinanislekdemir** [comment]
Instead of using docs/ directory, I will create gh-pages branch and let Github to serve documentations through github branch. This way, we can easily modify / replace existing docs with better looking alternatives.

**Comment by sinanislekdemir** [comment]
* Created orphan gh-pages branch
* Generated latest docs based on fixes done by @magandrez 
* Moved docs manually to gh-pages root
* Pushed gh-pages and setup github to serve directly from gh-pages branch.

**Comment by magandrez** [comment]
👌
