### ISSUE TITLE
Moving to vertical revert camera front/back view (flickering)

### ISSUE THREAD

**Issue by Kochise** [sinanislekdemir/payton#27]
Hi, using any example, when moving the camera above (or under) the scene (even empty) using "mouse right button", the camera flickers front/back very rapidly when it reaches the Z axis.

Could you disable/fix that "effect" ?

**Comment by sinanislekdemir** [comment]
Hi!

Thank you for the feedback and once again apologies for seeing this too late;
Nevertheless, https://github.com/sinanislekdemir/payton/commit/0d16a00cfe8a167543b1782720bfd45d89162821 this should be fixing the issue.

I also released a new version to pypi packages as `0.1.5` and should be available as the latest version with the fix.

**Comment by sinanislekdemir** [comment]
I would really appreciate if you can confirm if it's fixed @Kochise and I can close the issue;

**Comment by Kochise** [comment]
Hi, it's quite better indeed.

Some little things I noticed though :

`Unable to load numpy_formathandler accelerator from OpenGL_accelerate`

Tried to follow the steps there but to no avail :

https://stackoverflow.com/questions/61495735/unable-to-load-numpy-formathandler-accelerator-from-opengl-accelerate

Also :

```
In [1]: Traceback (most recent call last):

  File "C:\Users\dkoch\Downloads\payton_minimal.py", line 4, in <module>
    scene.run()

  File "C:\Program Files\Spyder\Python\lib\site-packages\payton\scene\scene.py", line 680, in run
    self._clear_context()

  File "C:\Program Files\Spyder\Python\lib\site-packages\payton\scene\scene.py", line 479, in _clear_context
    self.grid.destroy()

  File "C:\Program Files\Spyder\Python\lib\site-packages\payton\scene\grid.py", line 118, in destroy
    glDeleteVertexArrays(1, [self._vao])

  File "src/latebind.pyx", line 39, in OpenGL_accelerate.latebind.LateBind.__call__

  File "src/wrapper.pyx", line 311, in OpenGL_accelerate.wrapper.Wrapper.__call__

  File "C:\Program Files\Spyder\Python\lib\site-packages\OpenGL\platform\baseplatform.py", line 425, in __call__
    self.__name__, self.__name__,

NullFunctionError: Attempt to call an undefined function glDeleteVertexArrays, check for bool(glDeleteVertexArrays) before calling
```

And :

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
payton 0.1.5 requires numpy==1.18.2, but you have numpy 1.20.2 which is incompatible.
payton 0.1.5 requires PyOpenGL==3.1.3rc1, but you have pyopengl 3.1.5 which is incompatible.
```

Could the required versions be >= instead of strictly == ? I don't want to spawn too many venv just to solve the specific requirements of every package.
